const data = {
  products: [
    {
      name: 'AM65Less',
      slug: 'am65less',
      category: '65',
      image: '/images/am65.jpg',
      price: 400,
      countInStock: 0,
      brank: 'Angry Miao',
      rating: 4.5,
      numReviews: 10,
      description: 'A AM65less keyboard',
    },
    {
      name: 'Space65',
      slug: 'space65',
      category: '65',
      image: '/images/space65.jpg',
      price: 300,
      countInStock: 1,
      brank: 'Gray Studio',
      rating: 4.5,
      numReviews: 14,
      description: 'A Space65 keyboard',
    },
    {
      name: 'meta75',
      slug: 'meta75',
      category: '80',
      image: '/images/meta75.jpg',
      price: 500,
      countInStock: 1,
      brank: 'Matrix Lab',
      rating: 5,
      numReviews: 20,
      description: 'A Meta75 keyboard',
    },
    {
      name: 'Am AFA',
      slug: 'am-afa',
      category: '75',
      image: '/images/amafa.jpg',
      price: 600,
      countInStock: 1,
      brank: 'Angry Miao',
      rating: 4.0,
      numReviews: 100,
      description: 'A AmAFA keyboard',
    },
  ],
};

export default data;
